import {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowLeft, ArrowRight,
  Award,
  Banknote,
  BarChart3,
  Bell,
  BellRing,
  Bookmark,
  Building2,
  Calculator,
  Calendar,
  CalendarCheck, CalendarPlus,
  Camera,
  Check,
  CheckCheck,
  CheckCircle2,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  ClipboardList,
  Clock,
  Coins,
  Contact,
  Copy,
  CreditCard,
  DollarSign,
  Download,
  Edit,
  ExternalLink,
  Eye, EyeOff,
  File, FileCheck, FilePlus,
  FileText,
  Filter,
  Flag,
  FolderOpen,
  Fullscreen,
  Gauge,
  Gem,
  Gift,
  Globe,
  Grid,
  Grip,
  Hash,
  Heart,
  HelpCircle,
  Home,
  Image,
  Info,
  Key,
  Layers,
  LayoutDashboard,
  Lightbulb,
  LineChart,
  Link,
  List,
  Loader2,
  Lock,
  LogOut,
  Mail,
  MapPin,
  Maximize2,
  Medal,
  Megaphone,
  Menu,
  MessageCircle,
  MessageSquare,
  Minimize2,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Package, Palette,
  Paperclip,
  Percent,
  Phone,
  PieChart,
  Plus,
  Receipt,
  RefreshCw,
  Rocket,
  Save,
  Search,
  Send,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  Shirt,
  SortAsc,
  Sparkles,
  Star,
  Sun,
  Table,
  Tag,
  Target,
  Timer,
  Trash2,
  TrendingDown,
  TrendingUp,
  Trophy,
  Unlock,
  Upload,
  User,
  UserCheck,
  UserCog,
  UserMinus,
  UserPlus,
  Users,
  UserX,
  Video,
  Wallet, Wrench,
  X,
  XCircle,
  Zap,
  Reply,
  Smile,
  Swords,
  Crosshair,
  Crown
} from 'lucide-react'

// Use Circle as volleyball icon since Volleyball doesn't exist in lucide-react
export const VolleyballIcon = Circle

// Icon name to component mapping
export const iconMap = {
  // Navigation & Layout
  dashboard: LayoutDashboard,
  home: Home,
  menu: Menu,
  close: X,
  settings: Settings,
  
  // Users & People
  users: Users,
  user: User,
  'user-cog': UserCog,
  'user-plus': UserPlus,
  'user-minus': UserMinus,
  'user-check': UserCheck,
  'user-x': UserX,
  'users-round': Users,
  contact: Contact,
  
  // Content & Files
  clipboard: ClipboardList,
  file: File,
  'file-text': FileText,
  'file-check': FileCheck,
  'file-plus': FilePlus,
  folder: FolderOpen,
  document: FileText,
  
  // Actions
  plus: Plus,
  edit: Edit,
  trash: Trash2,
  save: Save,
  copy: Copy,
  download: Download,
  upload: Upload,
  share: Share2,
  send: Send,
  refresh: RefreshCw,
  search: Search,
  filter: Filter,
  sort: SortAsc,
  
  // Status & Feedback
  check: Check,
  'check-circle': CheckCircle2,
  'check-square': CheckSquare,
  x: X,
  'x-circle': XCircle,
  alert: AlertTriangle,
  'alert-circle': AlertCircle,
  info: Info,
  'help-circle': HelpCircle,
  loader: Loader2,
  
  // Communication
  message: MessageCircle,
  messages: MessageCircle,
  'message-square': MessageSquare,
  megaphone: Megaphone,
  bell: Bell,
  'bell-ring': BellRing,
  mail: Mail,
  phone: Phone,
  
  // Finance
  dollar: DollarSign,
  wallet: Wallet,
  'credit-card': CreditCard,
  banknote: Banknote,
  coins: Coins,
  receipt: Receipt,
  
  // Charts & Analytics
  'bar-chart': BarChart3,
  'line-chart': LineChart,
  'pie-chart': PieChart,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  activity: Activity,
  gauge: Gauge,
  
  // Time & Calendar
  calendar: Calendar,
  'calendar-days': Calendar,
  'calendar-check': CalendarCheck,
  'calendar-plus': CalendarPlus,
  clock: Clock,
  timer: Timer,
  
  // Sports & Games
  volleyball: VolleyballIcon,
  target: Target,
  trophy: Trophy,
  medal: Medal,
  award: Award,
  star: Star,
  flag: Flag,
  
  // UI Elements
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'more-vertical': MoreVertical,
  'more-horizontal': MoreHorizontal,
  grip: Grip,
  
  // View & Visibility
  eye: Eye,
  'eye-off': EyeOff,
  maximize: Maximize2,
  minimize: Minimize2,
  fullscreen: Fullscreen,
  
  // Media
  image: Image,
  camera: Camera,
  video: Video,
  paperclip: Paperclip,
  
  // Security
  shield: Shield,
  'shield-check': ShieldCheck,
  lock: Lock,
  unlock: Unlock,
  key: Key,
  
  // Location
  map: MapPin,
  'map-pin': MapPin,
  globe: Globe,
  building: Building2,
  
  // Features
  sparkles: Sparkles,
  rocket: Rocket,
  lightbulb: Lightbulb,
  zap: Zap,
  
  // Other
  bookmark: Bookmark,
  tag: Tag,
  hash: Hash,
  link: Link,
  external: ExternalLink,
  heart: Heart,
  gift: Gift,
  gem: Gem,
  package: Package,
  palette: Palette,
  wrench: Wrench,
  shirt: Shirt,
  moon: Moon,
  sun: Sun,
  logout: LogOut,
  layers: Layers,
  grid: Grid,
  list: List,
  table: Table,
  percent: Percent,
  calculator: Calculator,
}

// Re-export commonly used icons for direct imports
export {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowLeft, ArrowRight,
  Award,
  Banknote,
  BarChart3,
  Bell,
  BellRing,
  Bookmark,
  Building2,
  Calculator,
  Calendar,
  CalendarCheck, CalendarPlus,
  Camera,
  Check,
  CheckCircle2,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  ClipboardList,
  Clock,
  Coins,
  Contact,
  Copy,
  CreditCard,
  DollarSign,
  Download,
  Edit,
  ExternalLink,
  Eye, EyeOff,
  File, FileCheck, FilePlus,
  FileText,
  Filter,
  Flag,
  FolderOpen,
  Fullscreen,
  Gauge,
  Gem,
  Gift,
  Globe,
  Grid,
  Grip,
  Hash,
  Heart,
  HelpCircle,
  Home,
  Image,
  Info,
  Key,
  Layers,
  LayoutDashboard,
  Lightbulb,
  LineChart,
  Link,
  List,
  Loader2,
  Lock,
  LogOut,
  Mail,
  MapPin,
  Maximize2,
  Medal,
  Megaphone,
  Menu,
  MessageCircle,
  MessageSquare,
  Minimize2,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Package, Palette,
  Paperclip,
  Percent,
  Phone,
  PieChart,
  Plus,
  Receipt,
  RefreshCw,
  Rocket,
  Save,
  Search,
  Send,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  Shirt,
  SortAsc,
  Sparkles,
  Star,
  Sun,
  Table,
  Tag,
  Target,
  Timer,
  Trash2,
  TrendingDown,
  TrendingUp,
  Trophy,
  Unlock,
  Upload,
  User,
  UserCheck,
  UserCog,
  UserMinus,
  UserPlus,
  Users,
  UserX,
  Video,
  Wallet, Wrench,
  X,
  XCircle,
  Zap,
  Reply,
  Smile,
  CheckCheck,
  Swords,
  Crosshair,
  Crown
}
